/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowCleaningKadunaRouteImport } from './routes/window-cleaning-kaduna'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SofaUpholsteryCleaningKadunaRouteImport } from './routes/sofa-upholstery-cleaning-kaduna'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PostConstructionCleaningKadunaRouteImport } from './routes/post-construction-cleaning-kaduna'
import { Route as PestControlKadunaRouteImport } from './routes/pest-control-kaduna'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as OfficeCleaningKadunaRouteImport } from './routes/office-cleaning-kaduna'
import { Route as MoveInMoveOutCleaningKadunaRouteImport } from './routes/move-in-move-out-cleaning-kaduna'
import { Route as MosquitoControlKadunaRouteImport } from './routes/mosquito-control-kaduna'
import { Route as IndustrialCleaningKadunaRouteImport } from './routes/industrial-cleaning-kaduna'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HouseCleaningKadunaRouteImport } from './routes/house-cleaning-kaduna'
import { Route as FumigationServiceKadunaRouteImport } from './routes/fumigation-service-kaduna'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventCleaningKadunaRouteImport } from './routes/event-cleaning-kaduna'
import { Route as DisinfectionSanitizationKadunaRouteImport } from './routes/disinfection-sanitization-kaduna'
import { Route as DeepCleaningKadunaRouteImport } from './routes/deep-cleaning-kaduna'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CockroachTreatmentKadunaRouteImport } from './routes/cockroach-treatment-kaduna'
import { Route as CleaningServiceUngwanRimiKadunaRouteImport } from './routes/cleaning-service-ungwan-rimi-kaduna'
import { Route as CleaningServiceSabonGariKadunaRouteImport } from './routes/cleaning-service-sabon-gari-kaduna'
import { Route as CleaningServiceRigasaKadunaRouteImport } from './routes/cleaning-service-rigasa-kaduna'
import { Route as CleaningServiceNarayiKadunaRouteImport } from './routes/cleaning-service-narayi-kaduna'
import { Route as CleaningServiceKakuriKadunaRouteImport } from './routes/cleaning-service-kakuri-kaduna'
import { Route as CleaningServiceKadunaNorthRouteImport } from './routes/cleaning-service-kaduna-north'
import { Route as CleaningServiceKadunaGraRouteImport } from './routes/cleaning-service-kaduna-gra'
import { Route as CleaningServiceBarnawaKadunaRouteImport } from './routes/cleaning-service-barnawa-kaduna'
import { Route as CarpetCleaningKadunaRouteImport } from './routes/carpet-cleaning-kaduna'
import { Route as BedBugTreatmentKadunaRouteImport } from './routes/bed-bug-treatment-kaduna'
import { Route as AirbnbShortLetCleaningKadunaRouteImport } from './routes/airbnb-short-let-cleaning-kaduna'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WindowCleaningKadunaRoute = WindowCleaningKadunaRouteImport.update({
  id: '/window-cleaning-kaduna',
  path: '/window-cleaning-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SofaUpholsteryCleaningKadunaRoute =
  SofaUpholsteryCleaningKadunaRouteImport.update({
    id: '/sofa-upholstery-cleaning-kaduna',
    path: '/sofa-upholstery-cleaning-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostConstructionCleaningKadunaRoute =
  PostConstructionCleaningKadunaRouteImport.update({
    id: '/post-construction-cleaning-kaduna',
    path: '/post-construction-cleaning-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const PestControlKadunaRoute = PestControlKadunaRouteImport.update({
  id: '/pest-control-kaduna',
  path: '/pest-control-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeCleaningKadunaRoute = OfficeCleaningKadunaRouteImport.update({
  id: '/office-cleaning-kaduna',
  path: '/office-cleaning-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const MoveInMoveOutCleaningKadunaRoute =
  MoveInMoveOutCleaningKadunaRouteImport.update({
    id: '/move-in-move-out-cleaning-kaduna',
    path: '/move-in-move-out-cleaning-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const MosquitoControlKadunaRoute = MosquitoControlKadunaRouteImport.update({
  id: '/mosquito-control-kaduna',
  path: '/mosquito-control-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrialCleaningKadunaRoute =
  IndustrialCleaningKadunaRouteImport.update({
    id: '/industrial-cleaning-kaduna',
    path: '/industrial-cleaning-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseCleaningKadunaRoute = HouseCleaningKadunaRouteImport.update({
  id: '/house-cleaning-kaduna',
  path: '/house-cleaning-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const FumigationServiceKadunaRoute = FumigationServiceKadunaRouteImport.update({
  id: '/fumigation-service-kaduna',
  path: '/fumigation-service-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventCleaningKadunaRoute = EventCleaningKadunaRouteImport.update({
  id: '/event-cleaning-kaduna',
  path: '/event-cleaning-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const DisinfectionSanitizationKadunaRoute =
  DisinfectionSanitizationKadunaRouteImport.update({
    id: '/disinfection-sanitization-kaduna',
    path: '/disinfection-sanitization-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeepCleaningKadunaRoute = DeepCleaningKadunaRouteImport.update({
  id: '/deep-cleaning-kaduna',
  path: '/deep-cleaning-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CockroachTreatmentKadunaRoute =
  CockroachTreatmentKadunaRouteImport.update({
    id: '/cockroach-treatment-kaduna',
    path: '/cockroach-treatment-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceUngwanRimiKadunaRoute =
  CleaningServiceUngwanRimiKadunaRouteImport.update({
    id: '/cleaning-service-ungwan-rimi-kaduna',
    path: '/cleaning-service-ungwan-rimi-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceSabonGariKadunaRoute =
  CleaningServiceSabonGariKadunaRouteImport.update({
    id: '/cleaning-service-sabon-gari-kaduna',
    path: '/cleaning-service-sabon-gari-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceRigasaKadunaRoute =
  CleaningServiceRigasaKadunaRouteImport.update({
    id: '/cleaning-service-rigasa-kaduna',
    path: '/cleaning-service-rigasa-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceNarayiKadunaRoute =
  CleaningServiceNarayiKadunaRouteImport.update({
    id: '/cleaning-service-narayi-kaduna',
    path: '/cleaning-service-narayi-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceKakuriKadunaRoute =
  CleaningServiceKakuriKadunaRouteImport.update({
    id: '/cleaning-service-kakuri-kaduna',
    path: '/cleaning-service-kakuri-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceKadunaNorthRoute =
  CleaningServiceKadunaNorthRouteImport.update({
    id: '/cleaning-service-kaduna-north',
    path: '/cleaning-service-kaduna-north',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceKadunaGraRoute =
  CleaningServiceKadunaGraRouteImport.update({
    id: '/cleaning-service-kaduna-gra',
    path: '/cleaning-service-kaduna-gra',
    getParentRoute: () => rootRouteImport,
  } as any)
const CleaningServiceBarnawaKadunaRoute =
  CleaningServiceBarnawaKadunaRouteImport.update({
    id: '/cleaning-service-barnawa-kaduna',
    path: '/cleaning-service-barnawa-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const CarpetCleaningKadunaRoute = CarpetCleaningKadunaRouteImport.update({
  id: '/carpet-cleaning-kaduna',
  path: '/carpet-cleaning-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const BedBugTreatmentKadunaRoute = BedBugTreatmentKadunaRouteImport.update({
  id: '/bed-bug-treatment-kaduna',
  path: '/bed-bug-treatment-kaduna',
  getParentRoute: () => rootRouteImport,
} as any)
const AirbnbShortLetCleaningKadunaRoute =
  AirbnbShortLetCleaningKadunaRouteImport.update({
    id: '/airbnb-short-let-cleaning-kaduna',
    path: '/airbnb-short-let-cleaning-kaduna',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airbnb-short-let-cleaning-kaduna': typeof AirbnbShortLetCleaningKadunaRoute
  '/bed-bug-treatment-kaduna': typeof BedBugTreatmentKadunaRoute
  '/carpet-cleaning-kaduna': typeof CarpetCleaningKadunaRoute
  '/cleaning-service-barnawa-kaduna': typeof CleaningServiceBarnawaKadunaRoute
  '/cleaning-service-kaduna-gra': typeof CleaningServiceKadunaGraRoute
  '/cleaning-service-kaduna-north': typeof CleaningServiceKadunaNorthRoute
  '/cleaning-service-kakuri-kaduna': typeof CleaningServiceKakuriKadunaRoute
  '/cleaning-service-narayi-kaduna': typeof CleaningServiceNarayiKadunaRoute
  '/cleaning-service-rigasa-kaduna': typeof CleaningServiceRigasaKadunaRoute
  '/cleaning-service-sabon-gari-kaduna': typeof CleaningServiceSabonGariKadunaRoute
  '/cleaning-service-ungwan-rimi-kaduna': typeof CleaningServiceUngwanRimiKadunaRoute
  '/cockroach-treatment-kaduna': typeof CockroachTreatmentKadunaRoute
  '/contact': typeof ContactRoute
  '/deep-cleaning-kaduna': typeof DeepCleaningKadunaRoute
  '/disinfection-sanitization-kaduna': typeof DisinfectionSanitizationKadunaRoute
  '/event-cleaning-kaduna': typeof EventCleaningKadunaRoute
  '/faq': typeof FaqRoute
  '/fumigation-service-kaduna': typeof FumigationServiceKadunaRoute
  '/house-cleaning-kaduna': typeof HouseCleaningKadunaRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industrial-cleaning-kaduna': typeof IndustrialCleaningKadunaRoute
  '/mosquito-control-kaduna': typeof MosquitoControlKadunaRoute
  '/move-in-move-out-cleaning-kaduna': typeof MoveInMoveOutCleaningKadunaRoute
  '/office-cleaning-kaduna': typeof OfficeCleaningKadunaRoute
  '/our-team': typeof OurTeamRoute
  '/pest-control-kaduna': typeof PestControlKadunaRoute
  '/post-construction-cleaning-kaduna': typeof PostConstructionCleaningKadunaRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sofa-upholstery-cleaning-kaduna': typeof SofaUpholsteryCleaningKadunaRoute
  '/terms': typeof TermsRoute
  '/window-cleaning-kaduna': typeof WindowCleaningKadunaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airbnb-short-let-cleaning-kaduna': typeof AirbnbShortLetCleaningKadunaRoute
  '/bed-bug-treatment-kaduna': typeof BedBugTreatmentKadunaRoute
  '/carpet-cleaning-kaduna': typeof CarpetCleaningKadunaRoute
  '/cleaning-service-barnawa-kaduna': typeof CleaningServiceBarnawaKadunaRoute
  '/cleaning-service-kaduna-gra': typeof CleaningServiceKadunaGraRoute
  '/cleaning-service-kaduna-north': typeof CleaningServiceKadunaNorthRoute
  '/cleaning-service-kakuri-kaduna': typeof CleaningServiceKakuriKadunaRoute
  '/cleaning-service-narayi-kaduna': typeof CleaningServiceNarayiKadunaRoute
  '/cleaning-service-rigasa-kaduna': typeof CleaningServiceRigasaKadunaRoute
  '/cleaning-service-sabon-gari-kaduna': typeof CleaningServiceSabonGariKadunaRoute
  '/cleaning-service-ungwan-rimi-kaduna': typeof CleaningServiceUngwanRimiKadunaRoute
  '/cockroach-treatment-kaduna': typeof CockroachTreatmentKadunaRoute
  '/contact': typeof ContactRoute
  '/deep-cleaning-kaduna': typeof DeepCleaningKadunaRoute
  '/disinfection-sanitization-kaduna': typeof DisinfectionSanitizationKadunaRoute
  '/event-cleaning-kaduna': typeof EventCleaningKadunaRoute
  '/faq': typeof FaqRoute
  '/fumigation-service-kaduna': typeof FumigationServiceKadunaRoute
  '/house-cleaning-kaduna': typeof HouseCleaningKadunaRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industrial-cleaning-kaduna': typeof IndustrialCleaningKadunaRoute
  '/mosquito-control-kaduna': typeof MosquitoControlKadunaRoute
  '/move-in-move-out-cleaning-kaduna': typeof MoveInMoveOutCleaningKadunaRoute
  '/office-cleaning-kaduna': typeof OfficeCleaningKadunaRoute
  '/our-team': typeof OurTeamRoute
  '/pest-control-kaduna': typeof PestControlKadunaRoute
  '/post-construction-cleaning-kaduna': typeof PostConstructionCleaningKadunaRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sofa-upholstery-cleaning-kaduna': typeof SofaUpholsteryCleaningKadunaRoute
  '/terms': typeof TermsRoute
  '/window-cleaning-kaduna': typeof WindowCleaningKadunaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airbnb-short-let-cleaning-kaduna': typeof AirbnbShortLetCleaningKadunaRoute
  '/bed-bug-treatment-kaduna': typeof BedBugTreatmentKadunaRoute
  '/carpet-cleaning-kaduna': typeof CarpetCleaningKadunaRoute
  '/cleaning-service-barnawa-kaduna': typeof CleaningServiceBarnawaKadunaRoute
  '/cleaning-service-kaduna-gra': typeof CleaningServiceKadunaGraRoute
  '/cleaning-service-kaduna-north': typeof CleaningServiceKadunaNorthRoute
  '/cleaning-service-kakuri-kaduna': typeof CleaningServiceKakuriKadunaRoute
  '/cleaning-service-narayi-kaduna': typeof CleaningServiceNarayiKadunaRoute
  '/cleaning-service-rigasa-kaduna': typeof CleaningServiceRigasaKadunaRoute
  '/cleaning-service-sabon-gari-kaduna': typeof CleaningServiceSabonGariKadunaRoute
  '/cleaning-service-ungwan-rimi-kaduna': typeof CleaningServiceUngwanRimiKadunaRoute
  '/cockroach-treatment-kaduna': typeof CockroachTreatmentKadunaRoute
  '/contact': typeof ContactRoute
  '/deep-cleaning-kaduna': typeof DeepCleaningKadunaRoute
  '/disinfection-sanitization-kaduna': typeof DisinfectionSanitizationKadunaRoute
  '/event-cleaning-kaduna': typeof EventCleaningKadunaRoute
  '/faq': typeof FaqRoute
  '/fumigation-service-kaduna': typeof FumigationServiceKadunaRoute
  '/house-cleaning-kaduna': typeof HouseCleaningKadunaRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industrial-cleaning-kaduna': typeof IndustrialCleaningKadunaRoute
  '/mosquito-control-kaduna': typeof MosquitoControlKadunaRoute
  '/move-in-move-out-cleaning-kaduna': typeof MoveInMoveOutCleaningKadunaRoute
  '/office-cleaning-kaduna': typeof OfficeCleaningKadunaRoute
  '/our-team': typeof OurTeamRoute
  '/pest-control-kaduna': typeof PestControlKadunaRoute
  '/post-construction-cleaning-kaduna': typeof PostConstructionCleaningKadunaRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sofa-upholstery-cleaning-kaduna': typeof SofaUpholsteryCleaningKadunaRoute
  '/terms': typeof TermsRoute
  '/window-cleaning-kaduna': typeof WindowCleaningKadunaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airbnb-short-let-cleaning-kaduna'
    | '/bed-bug-treatment-kaduna'
    | '/carpet-cleaning-kaduna'
    | '/cleaning-service-barnawa-kaduna'
    | '/cleaning-service-kaduna-gra'
    | '/cleaning-service-kaduna-north'
    | '/cleaning-service-kakuri-kaduna'
    | '/cleaning-service-narayi-kaduna'
    | '/cleaning-service-rigasa-kaduna'
    | '/cleaning-service-sabon-gari-kaduna'
    | '/cleaning-service-ungwan-rimi-kaduna'
    | '/cockroach-treatment-kaduna'
    | '/contact'
    | '/deep-cleaning-kaduna'
    | '/disinfection-sanitization-kaduna'
    | '/event-cleaning-kaduna'
    | '/faq'
    | '/fumigation-service-kaduna'
    | '/house-cleaning-kaduna'
    | '/how-it-works'
    | '/industrial-cleaning-kaduna'
    | '/mosquito-control-kaduna'
    | '/move-in-move-out-cleaning-kaduna'
    | '/office-cleaning-kaduna'
    | '/our-team'
    | '/pest-control-kaduna'
    | '/post-construction-cleaning-kaduna'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/service-areas'
    | '/sitemap.xml'
    | '/sofa-upholstery-cleaning-kaduna'
    | '/terms'
    | '/window-cleaning-kaduna'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airbnb-short-let-cleaning-kaduna'
    | '/bed-bug-treatment-kaduna'
    | '/carpet-cleaning-kaduna'
    | '/cleaning-service-barnawa-kaduna'
    | '/cleaning-service-kaduna-gra'
    | '/cleaning-service-kaduna-north'
    | '/cleaning-service-kakuri-kaduna'
    | '/cleaning-service-narayi-kaduna'
    | '/cleaning-service-rigasa-kaduna'
    | '/cleaning-service-sabon-gari-kaduna'
    | '/cleaning-service-ungwan-rimi-kaduna'
    | '/cockroach-treatment-kaduna'
    | '/contact'
    | '/deep-cleaning-kaduna'
    | '/disinfection-sanitization-kaduna'
    | '/event-cleaning-kaduna'
    | '/faq'
    | '/fumigation-service-kaduna'
    | '/house-cleaning-kaduna'
    | '/how-it-works'
    | '/industrial-cleaning-kaduna'
    | '/mosquito-control-kaduna'
    | '/move-in-move-out-cleaning-kaduna'
    | '/office-cleaning-kaduna'
    | '/our-team'
    | '/pest-control-kaduna'
    | '/post-construction-cleaning-kaduna'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/service-areas'
    | '/sitemap.xml'
    | '/sofa-upholstery-cleaning-kaduna'
    | '/terms'
    | '/window-cleaning-kaduna'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/airbnb-short-let-cleaning-kaduna'
    | '/bed-bug-treatment-kaduna'
    | '/carpet-cleaning-kaduna'
    | '/cleaning-service-barnawa-kaduna'
    | '/cleaning-service-kaduna-gra'
    | '/cleaning-service-kaduna-north'
    | '/cleaning-service-kakuri-kaduna'
    | '/cleaning-service-narayi-kaduna'
    | '/cleaning-service-rigasa-kaduna'
    | '/cleaning-service-sabon-gari-kaduna'
    | '/cleaning-service-ungwan-rimi-kaduna'
    | '/cockroach-treatment-kaduna'
    | '/contact'
    | '/deep-cleaning-kaduna'
    | '/disinfection-sanitization-kaduna'
    | '/event-cleaning-kaduna'
    | '/faq'
    | '/fumigation-service-kaduna'
    | '/house-cleaning-kaduna'
    | '/how-it-works'
    | '/industrial-cleaning-kaduna'
    | '/mosquito-control-kaduna'
    | '/move-in-move-out-cleaning-kaduna'
    | '/office-cleaning-kaduna'
    | '/our-team'
    | '/pest-control-kaduna'
    | '/post-construction-cleaning-kaduna'
    | '/pricing'
    | '/privacy-policy'
    | '/robots.txt'
    | '/service-areas'
    | '/sitemap.xml'
    | '/sofa-upholstery-cleaning-kaduna'
    | '/terms'
    | '/window-cleaning-kaduna'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirbnbShortLetCleaningKadunaRoute: typeof AirbnbShortLetCleaningKadunaRoute
  BedBugTreatmentKadunaRoute: typeof BedBugTreatmentKadunaRoute
  CarpetCleaningKadunaRoute: typeof CarpetCleaningKadunaRoute
  CleaningServiceBarnawaKadunaRoute: typeof CleaningServiceBarnawaKadunaRoute
  CleaningServiceKadunaGraRoute: typeof CleaningServiceKadunaGraRoute
  CleaningServiceKadunaNorthRoute: typeof CleaningServiceKadunaNorthRoute
  CleaningServiceKakuriKadunaRoute: typeof CleaningServiceKakuriKadunaRoute
  CleaningServiceNarayiKadunaRoute: typeof CleaningServiceNarayiKadunaRoute
  CleaningServiceRigasaKadunaRoute: typeof CleaningServiceRigasaKadunaRoute
  CleaningServiceSabonGariKadunaRoute: typeof CleaningServiceSabonGariKadunaRoute
  CleaningServiceUngwanRimiKadunaRoute: typeof CleaningServiceUngwanRimiKadunaRoute
  CockroachTreatmentKadunaRoute: typeof CockroachTreatmentKadunaRoute
  ContactRoute: typeof ContactRoute
  DeepCleaningKadunaRoute: typeof DeepCleaningKadunaRoute
  DisinfectionSanitizationKadunaRoute: typeof DisinfectionSanitizationKadunaRoute
  EventCleaningKadunaRoute: typeof EventCleaningKadunaRoute
  FaqRoute: typeof FaqRoute
  FumigationServiceKadunaRoute: typeof FumigationServiceKadunaRoute
  HouseCleaningKadunaRoute: typeof HouseCleaningKadunaRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustrialCleaningKadunaRoute: typeof IndustrialCleaningKadunaRoute
  MosquitoControlKadunaRoute: typeof MosquitoControlKadunaRoute
  MoveInMoveOutCleaningKadunaRoute: typeof MoveInMoveOutCleaningKadunaRoute
  OfficeCleaningKadunaRoute: typeof OfficeCleaningKadunaRoute
  OurTeamRoute: typeof OurTeamRoute
  PestControlKadunaRoute: typeof PestControlKadunaRoute
  PostConstructionCleaningKadunaRoute: typeof PostConstructionCleaningKadunaRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SofaUpholsteryCleaningKadunaRoute: typeof SofaUpholsteryCleaningKadunaRoute
  TermsRoute: typeof TermsRoute
  WindowCleaningKadunaRoute: typeof WindowCleaningKadunaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window-cleaning-kaduna': {
      id: '/window-cleaning-kaduna'
      path: '/window-cleaning-kaduna'
      fullPath: '/window-cleaning-kaduna'
      preLoaderRoute: typeof WindowCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sofa-upholstery-cleaning-kaduna': {
      id: '/sofa-upholstery-cleaning-kaduna'
      path: '/sofa-upholstery-cleaning-kaduna'
      fullPath: '/sofa-upholstery-cleaning-kaduna'
      preLoaderRoute: typeof SofaUpholsteryCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-construction-cleaning-kaduna': {
      id: '/post-construction-cleaning-kaduna'
      path: '/post-construction-cleaning-kaduna'
      fullPath: '/post-construction-cleaning-kaduna'
      preLoaderRoute: typeof PostConstructionCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-control-kaduna': {
      id: '/pest-control-kaduna'
      path: '/pest-control-kaduna'
      fullPath: '/pest-control-kaduna'
      preLoaderRoute: typeof PestControlKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office-cleaning-kaduna': {
      id: '/office-cleaning-kaduna'
      path: '/office-cleaning-kaduna'
      fullPath: '/office-cleaning-kaduna'
      preLoaderRoute: typeof OfficeCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/move-in-move-out-cleaning-kaduna': {
      id: '/move-in-move-out-cleaning-kaduna'
      path: '/move-in-move-out-cleaning-kaduna'
      fullPath: '/move-in-move-out-cleaning-kaduna'
      preLoaderRoute: typeof MoveInMoveOutCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosquito-control-kaduna': {
      id: '/mosquito-control-kaduna'
      path: '/mosquito-control-kaduna'
      fullPath: '/mosquito-control-kaduna'
      preLoaderRoute: typeof MosquitoControlKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrial-cleaning-kaduna': {
      id: '/industrial-cleaning-kaduna'
      path: '/industrial-cleaning-kaduna'
      fullPath: '/industrial-cleaning-kaduna'
      preLoaderRoute: typeof IndustrialCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-cleaning-kaduna': {
      id: '/house-cleaning-kaduna'
      path: '/house-cleaning-kaduna'
      fullPath: '/house-cleaning-kaduna'
      preLoaderRoute: typeof HouseCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fumigation-service-kaduna': {
      id: '/fumigation-service-kaduna'
      path: '/fumigation-service-kaduna'
      fullPath: '/fumigation-service-kaduna'
      preLoaderRoute: typeof FumigationServiceKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-cleaning-kaduna': {
      id: '/event-cleaning-kaduna'
      path: '/event-cleaning-kaduna'
      fullPath: '/event-cleaning-kaduna'
      preLoaderRoute: typeof EventCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disinfection-sanitization-kaduna': {
      id: '/disinfection-sanitization-kaduna'
      path: '/disinfection-sanitization-kaduna'
      fullPath: '/disinfection-sanitization-kaduna'
      preLoaderRoute: typeof DisinfectionSanitizationKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-cleaning-kaduna': {
      id: '/deep-cleaning-kaduna'
      path: '/deep-cleaning-kaduna'
      fullPath: '/deep-cleaning-kaduna'
      preLoaderRoute: typeof DeepCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cockroach-treatment-kaduna': {
      id: '/cockroach-treatment-kaduna'
      path: '/cockroach-treatment-kaduna'
      fullPath: '/cockroach-treatment-kaduna'
      preLoaderRoute: typeof CockroachTreatmentKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-ungwan-rimi-kaduna': {
      id: '/cleaning-service-ungwan-rimi-kaduna'
      path: '/cleaning-service-ungwan-rimi-kaduna'
      fullPath: '/cleaning-service-ungwan-rimi-kaduna'
      preLoaderRoute: typeof CleaningServiceUngwanRimiKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-sabon-gari-kaduna': {
      id: '/cleaning-service-sabon-gari-kaduna'
      path: '/cleaning-service-sabon-gari-kaduna'
      fullPath: '/cleaning-service-sabon-gari-kaduna'
      preLoaderRoute: typeof CleaningServiceSabonGariKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-rigasa-kaduna': {
      id: '/cleaning-service-rigasa-kaduna'
      path: '/cleaning-service-rigasa-kaduna'
      fullPath: '/cleaning-service-rigasa-kaduna'
      preLoaderRoute: typeof CleaningServiceRigasaKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-narayi-kaduna': {
      id: '/cleaning-service-narayi-kaduna'
      path: '/cleaning-service-narayi-kaduna'
      fullPath: '/cleaning-service-narayi-kaduna'
      preLoaderRoute: typeof CleaningServiceNarayiKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-kakuri-kaduna': {
      id: '/cleaning-service-kakuri-kaduna'
      path: '/cleaning-service-kakuri-kaduna'
      fullPath: '/cleaning-service-kakuri-kaduna'
      preLoaderRoute: typeof CleaningServiceKakuriKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-kaduna-north': {
      id: '/cleaning-service-kaduna-north'
      path: '/cleaning-service-kaduna-north'
      fullPath: '/cleaning-service-kaduna-north'
      preLoaderRoute: typeof CleaningServiceKadunaNorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-kaduna-gra': {
      id: '/cleaning-service-kaduna-gra'
      path: '/cleaning-service-kaduna-gra'
      fullPath: '/cleaning-service-kaduna-gra'
      preLoaderRoute: typeof CleaningServiceKadunaGraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning-service-barnawa-kaduna': {
      id: '/cleaning-service-barnawa-kaduna'
      path: '/cleaning-service-barnawa-kaduna'
      fullPath: '/cleaning-service-barnawa-kaduna'
      preLoaderRoute: typeof CleaningServiceBarnawaKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carpet-cleaning-kaduna': {
      id: '/carpet-cleaning-kaduna'
      path: '/carpet-cleaning-kaduna'
      fullPath: '/carpet-cleaning-kaduna'
      preLoaderRoute: typeof CarpetCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bed-bug-treatment-kaduna': {
      id: '/bed-bug-treatment-kaduna'
      path: '/bed-bug-treatment-kaduna'
      fullPath: '/bed-bug-treatment-kaduna'
      preLoaderRoute: typeof BedBugTreatmentKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airbnb-short-let-cleaning-kaduna': {
      id: '/airbnb-short-let-cleaning-kaduna'
      path: '/airbnb-short-let-cleaning-kaduna'
      fullPath: '/airbnb-short-let-cleaning-kaduna'
      preLoaderRoute: typeof AirbnbShortLetCleaningKadunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirbnbShortLetCleaningKadunaRoute: AirbnbShortLetCleaningKadunaRoute,
  BedBugTreatmentKadunaRoute: BedBugTreatmentKadunaRoute,
  CarpetCleaningKadunaRoute: CarpetCleaningKadunaRoute,
  CleaningServiceBarnawaKadunaRoute: CleaningServiceBarnawaKadunaRoute,
  CleaningServiceKadunaGraRoute: CleaningServiceKadunaGraRoute,
  CleaningServiceKadunaNorthRoute: CleaningServiceKadunaNorthRoute,
  CleaningServiceKakuriKadunaRoute: CleaningServiceKakuriKadunaRoute,
  CleaningServiceNarayiKadunaRoute: CleaningServiceNarayiKadunaRoute,
  CleaningServiceRigasaKadunaRoute: CleaningServiceRigasaKadunaRoute,
  CleaningServiceSabonGariKadunaRoute: CleaningServiceSabonGariKadunaRoute,
  CleaningServiceUngwanRimiKadunaRoute: CleaningServiceUngwanRimiKadunaRoute,
  CockroachTreatmentKadunaRoute: CockroachTreatmentKadunaRoute,
  ContactRoute: ContactRoute,
  DeepCleaningKadunaRoute: DeepCleaningKadunaRoute,
  DisinfectionSanitizationKadunaRoute: DisinfectionSanitizationKadunaRoute,
  EventCleaningKadunaRoute: EventCleaningKadunaRoute,
  FaqRoute: FaqRoute,
  FumigationServiceKadunaRoute: FumigationServiceKadunaRoute,
  HouseCleaningKadunaRoute: HouseCleaningKadunaRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustrialCleaningKadunaRoute: IndustrialCleaningKadunaRoute,
  MosquitoControlKadunaRoute: MosquitoControlKadunaRoute,
  MoveInMoveOutCleaningKadunaRoute: MoveInMoveOutCleaningKadunaRoute,
  OfficeCleaningKadunaRoute: OfficeCleaningKadunaRoute,
  OurTeamRoute: OurTeamRoute,
  PestControlKadunaRoute: PestControlKadunaRoute,
  PostConstructionCleaningKadunaRoute: PostConstructionCleaningKadunaRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SofaUpholsteryCleaningKadunaRoute: SofaUpholsteryCleaningKadunaRoute,
  TermsRoute: TermsRoute,
  WindowCleaningKadunaRoute: WindowCleaningKadunaRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
